name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same API as Amazon AWS S3.
version: 0.12.14
homepage: https://github.com/nbspou/dospace
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.15.0
  crypto: ^3.0.5
  http: ^1.2.2
  xml: ^6.5.0

dev_dependencies:
  test: ^1.0.0
  ini: ^2.1.0-beta
